package com.order.ecommerceshop.dto.request;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.PositiveOrZero;
import jakarta.validation.constraints.Size;
import lombok.Data;

import java.math.BigDecimal;

@Data
@Schema(description = "Product input - partial updates allowed. " +
        "Only send fields you want to change. Omit fields for no change.")
public class ProductInput
{
    @Schema(description = "Product ID (autogenerated)", example = "1", accessMode = Schema.AccessMode.READ_ONLY)
    private Long id;

    @Size(min = 2, max = 150, message =" Name must be 2-150 characters")
    @Schema(description = "Product name", example = "Dress", nullable = true)
    private String name;

    @Size(max = 1000, message = "Description too long")
    @Schema(description = "Product description", example = "Latest i phone model", nullable = true)
    private String description;

    @Positive(message = "Price must be greater than 0")
    @Schema(description = "Product price", example = "89000.00", nullable = true)
    private BigDecimal price;

    @PositiveOrZero(message = "Quantity cannot be negative")
    @Schema(description = "Stock quantity", example = "50", nullable = true)
    private Integer stockQuantity;

    @Size(max = 100)
    @Schema(description = "Category", example = "Electronics", nullable = true)
    private String category;

    @Size(max = 500)
    @Schema(description = "Image URL", example = "http://image.com", nullable = true)
    private String imageUrl;
}
