spring.application.name=E-CommerceShop

# Default profile
spring.profiles.active=local

# Server
server.port=8085

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Actuator
management.endpoints.web.exposure.include=health,info,metrics