spring.application.name=E-CommerceShop
spring.datasource.url=jdbc:mysql://localhost:3306/myshop
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.graphql.graphiql.enabled=true

logging.level.com.order.ecommerceshop.service=DEBUG

# show Error Details on GraphQL webpage
spring.graphql.exception-handling.enabled=true


# JWT
app.jwt.secret=mySuperSecretKeyForJWTTokenGenerationThatIsAtLeast256BitsLong!!
app.jwt.expiration=86400000

# mail configuration for forgot password
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rupalikishore3011@gmail.com
spring.mail.password=dpuzijlmlexbqjhr

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# for(reset link)  frontend url
app.frontend.url=http://localhost:8081
# for reset token expiry
app.reset.token.expiry=900000

# bootstrap admin configuration
app.bootstrap.admin.enabled=true

# admin credential (Environment variable use in production)
app.bootstrap.admin.email=rupalikishore3011@gmail.com
app.bootstrap.admin.password=Shivba#@14359264
app.bootstrap.admin.name=Rupali Kishore
app.bootstrap.admin.address=Pune, Maharashtra
#
#app.bootstrap.admin.email=${ADMIN_EMAIL:admin@mystore.com}
#app.bootstrap.admin.password=${ADMIN_PASSWORD:changeme123}

## for development error details
#spring.graphql.exception-handling.enabled=true
#server.error.include-message=always
#server.error.include-stacktrace=always
#server.error.include-binding-errors=always
server.port=8085



